name: 'AgentMesh Lineage Check'
description: 'Check PR lineage coverage and optionally verify AgentMesh witness signatures'

inputs:
  require-trailers:
    description: 'If true, exit 1 when coverage < 100%'
    required: false
    default: 'false'
  verify-witness:
    description: 'If true, verify AgentMesh witness signatures for PR commits'
    required: false
    default: 'false'
  require-witness:
    description: 'If true, exit 1 when witness coverage < 100% (requires verify-witness=true)'
    required: false
    default: 'false'
  comment-on-pr:
    description: 'Post/update sticky PR comment with results'
    required: false
    default: 'true'
  github-token:
    description: 'Token for GitHub API calls'
    required: false
    default: ${{ github.token }}

outputs:
  commits-total:
    description: 'Total commits in PR'
    value: ${{ steps.check.outputs.commits-total }}
  commits-traced:
    description: 'Commits with AgentMesh-Episode trailer'
    value: ${{ steps.check.outputs.commits-traced }}
  coverage-pct:
    description: 'Lineage coverage percentage (0-100)'
    value: ${{ steps.check.outputs.coverage-pct }}
  unique-episodes:
    description: 'Count of distinct episode IDs'
    value: ${{ steps.check.outputs.unique-episodes }}
  files-changed:
    description: 'Files changed across PR'
    value: ${{ steps.check.outputs.files-changed }}
  witness-present:
    description: 'Commits with witness trailers present'
    value: ${{ steps.check.outputs.witness-present }}
  witness-verified:
    description: 'Commits whose witness signatures verified'
    value: ${{ steps.check.outputs.witness-verified }}
  witness-coverage-pct:
    description: 'Witness verification coverage percentage across PR commits (0-100)'
    value: ${{ steps.check.outputs.witness-coverage-pct }}
  result:
    description: 'PASS or FAIL'
    value: ${{ steps.check.outputs.result }}
  badge-url:
    description: 'shields.io badge URL for README embedding'
    value: ${{ steps.check.outputs.badge-url }}

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Python for witness verification
      if: inputs.verify-witness == 'true'
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install AgentMesh witness verifier
      if: inputs.verify-witness == 'true'
      shell: bash
      run: pip install "agentmesh-core[witness]>=0.6.0"

    - name: Check provenance trailers
      id: check
      shell: bash
      run: bash ${{ github.action_path }}/scripts/check-provenance.sh
      env:
        GITHUB_BASE_SHA: ${{ github.event.pull_request.base.sha }}
        GITHUB_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        REQUIRE_TRAILERS: ${{ inputs.require-trailers }}
        VERIFY_WITNESS: ${{ inputs.verify-witness }}
        REQUIRE_WITNESS: ${{ inputs.require-witness }}

    - name: Post PR comment
      if: github.event_name == 'pull_request' && inputs.comment-on-pr == 'true'
      continue-on-error: true
      shell: bash
      run: bash ${{ github.action_path }}/scripts/post-comment.sh
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        COMMENT_BODY_FILE: ${{ steps.check.outputs.comment-body-file }}
